trigger:
- main


schedules:
- cron: '57 23 * * 1'
  displayName: Weekly build to keep cache warm
  branches:
    include:
    - main
    
jobs:
- job: 'RunMATLABBuild'
 
  pool:
    vmImage: $(PLATFORM)

  strategy:
    matrix:    
      windows-MATLAB-R2021a:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2022b
      linux-MATLAB-R2021a:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2022b
      mac-MATLAB-R2021a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2022b
        
      windows-MATLAB-R2024a:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2024a
      linux-MATLAB-R2024a:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2024a
      mac-MATLAB-R2024a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2024a

        
  variables: 
  - group: matlab-batch-license
 
  steps:
  - task: Cache@2
    inputs:
      key: MATLAB-$(MATLAB_RELEASE)-$(PLATFORM)-20240329
      path: $(AGENT_TOOLSDIRECTORY)/MATLAB
  - task: InstallMATLAB@1
    inputs:
      release: $(MATLAB_RELEASE)
      products: >
        MATLAB
        MATLAB_Compiler
        MATLAB_Compiler_SDK
        Database_Toolbox
        Datafeed_Toolbox
        Econometrics_Toolbox
        Financial_Instruments_Toolbox
        Financial_Toolbox
        Optimization_Toolbox
        Parallel_Computing_Toolbox
        Statistics_and_Machine_Learning_Toolbox
 
  # This task Runs all the MATLAB and Simulink tests and generate variety of test artifacts. Check the documentation for all supported task parameters.
  - task: RunMATLABBuild@0
    inputs:
      tasks: test
    env:
      MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
       
