trigger:
- main


schedules:
- cron: '57 23 * * 1'
  displayName: Weekly build to keep cache warm
  branches:
    include:
    - main
    
jobs:
- job: 'RunMATLABBuild'
 
  pool:
    vmImage: $(PLATFORM)

  strategy:
    matrix:    
      windows-MATLAB-R2023a:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2023a
      linux-MATLAB-R2023a:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2023a
      mac-MATLAB-R2023a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2023a
        
      windows-MATLAB-R2024a:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2024a
      linux-MATLAB-R2024a:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2024a
      mac-MATLAB-R2024a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2024a

        
  variables: 
  - group: matlab-batch-license
 
  steps:
  #- task: Cache@2
   # inputs:
    #  key: MATLAB-$(MATLAB_RELEASE) | $(PLATFORM) | azure-pipelines.yml
     # path: $(AGENT_TOOLSDIRECTORY)/MATLAB
      
  - task: InstallMATLAB@1
    inputs:
      release: $(MATLAB_RELEASE)
      products: >
        MATLAB
        MATLAB_Compiler
        MATLAB_Compiler_SDK
        MATLAB_Test
  
  - task: RunMATLABBuild@1
    inputs:
      tasks: test
      
    env:
      MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
       
