# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on: 
  push:                       # Runs on push events
  pull_request:               # Runs on pull requests
  workflow_dispatch:          # Allows you to run this workflow manually from the Actions tab
    
jobs:
  # This workflow contains a single job called "build"


  compile-and-test:
    strategy:
      matrix:
        release: [R2022b, R2023a]
        platform: [ubuntu-latest, windows-latest, macos-latest]
        
    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.release }}-${{ matrix.platform }}
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.release }}

      # Runs a set of commands using the runners shell
      - name: Generate mex files & run tests
        uses: matlab-actions/run-build@v1
        with: 
          tasks: test

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: Test-Artifacts-${{ matrix.release }}-${{ matrix.platform }}
          # A file, directory or wildcard pattern that describes what to uplod
          path: toolbox/test-results.mat
          
      - name: Upload Mex Files
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: Mex-Artifacts-${{ matrix.release }}-${{ matrix.platform }}
          # A file, directory or wildcard pattern that describes what to upload
          path: toolbox/**/*.mex*64

          
  create-R2022b-toolbox:
    needs: compile-and-test 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: R2022b-ubuntu-latest

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta

      - name: Download mac artifacts
        if: ${{ always() }}
        uses: actions/download-artifact@v3
        with:
          name: Mex-Artifacts-R2022b-macos-latest
          path: toolbox
      - name: Download windows artifacts
        if: ${{ always() }}
        uses: actions/download-artifact@v3
        with:
          name: Mex-Artifacts-R2022b-windows-latest
          path: toolbox
      - name: Download linux artifacts
        if: ${{ always() }}
        uses: actions/download-artifact@v3
        with:
          name: Mex-Artifacts-R2022b-ubuntu-latest
          path: toolbox

      # Runs a set of commands using the runners shell
      - name: Run toolbox build
        uses: matlab-actions/run-build@v1
        with: 
          tasks: toolbox
     
      - name: Upload Toolbox
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: Toolbox Package
          # A file, directory or wildcard pattern that describes what to upload
          path: release/Mass-Spring-Damper.mltbx

  
